import google.generativeai as genai
import PIL.Image
from io import BytesIO

class MedicalImageAnalyzer:
    def __init__(self, api_key: str):
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-2.5-flash-lite')

    def analyze_image(self, image_bytes: bytes, mime_type: str) -> str:
        try:
            try:
                image = PIL.Image.open(BytesIO(image_bytes))
            except Exception:
                return "Error: The file provided is not a valid image or is corrupted. Please upload a standard image file (JPG, PNG)."

            prompt = """
            You are a highly experienced medical imaging specialist. 
            Analyze this medical image in detail.
            
            Please provide the output in the following Markdown format:
            
            ## Preliminary Analysis
            [Describe the visible anatomical structures and any anomalies observed]
            
            ## Potential Findings
            [List potential conditions or findings based on the visual evidence]
            
            ## Recommendations
            [Suggest further diagnostic steps or consultations]
            
            **Disclaimer:** This analysis is generated by AI and is for assistance purposes only. It is NOT a professional medical diagnosis.
            """
            
            response = self.model.generate_content([prompt, image])
            return response.text
        except Exception as e:
            print(f"Image Analysis Error: {e}")
            raise e
